name: CD on Main Branch Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Kubernetes CLI
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.2"

      # Step 3: Authenticate with Kubernetes Cluster
      - name: Authenticate with Kubernetes Cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $KUBECONFIG

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t your-registry/your-app:${{ github.sha }} .
          docker push your-registry/your-app:${{ github.sha }}

      # Step 5: Update Kubernetes Deployment
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/your-deployment your-container=your-registry/your-app:${{ github.sha }}
          kubectl rollout status deployment/your-deployment